### ISSUE TITLE
Error: input= must be a single character string containing a file name, a system command containing at least one space

### ISSUE THREAD

**Issue by 54sym** [sahwa/vcf_to_chromopainter#2]
when i run the command "Rscript vcf_to_chromopainter_main.R -g $input_d/$input_f -u FALSE -o output", it gives error message like this:

Running in classic chromopainter mode!
Successfully souced and compiled source code!
Making recombination rates file
Error: input= must be a single character string containing a file name, a system command containing at least one space, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or, the input data itself containing at least one \n or \r
Execution halted
<img width="863" alt="截屏2024-06-04 19 45 39" src="https://github.com/sahwa/vcf_to_chromopainter/assets/140576853/ccf46811-adfa-445b-9440-80e94cbec9d5">

**Comment by sahwa** [comment]
Hello, thanks for the issue.

It seems like you didn't include the genetic map, but that's my fault since I didn't update the readme. 

You need to include another argument ``--genmap``, which is a plink formatted genetic map, which you can download here `https://bochet.gcc.biostat.washington.edu/beagle/genetic_maps/` - you can ``wget`` the one which corresponds to your genome build, unzip them and then there should be a file for each chromosome. 

That should work, but let me know if you need any other help.

Best,

Sam

**Comment by 54sym** [comment]
> Hello, thanks for the issue.
> 
> It seems like you didn't include the genetic map, but that's my fault since I didn't update the readme.
> 
> You need to include another argument `--genmap`, which is a plink formatted genetic map, which you can download here `https://bochet.gcc.biostat.washington.edu/beagle/genetic_maps/` - you can `wget` the one which corresponds to your genome build, unzip them and then there should be a file for each chromosome.
> 
> That should work, but let me know if you need any other help.
> 
> Best,
> 
> Sam

Thanks , it works !!
